PADV-35: added Switch in active column to change it.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #14
Opened 2021-12-17 18:41 UTC by elvinquero

### Description
This PR adds a switch input to then make a API call to change the active field on InstitutionAdmin.

For reference: [PADV-35](https://agile-jira.pearson.com/browse/PADV-35)

### Images:
![admin7](https://user-images.githubusercontent.com/401198/146591981-9fd8f2ff-9298-4444-bcb4-280267cb8918.png)

2021-12-17 20:15 UTC, ivanvgh requested changes

2021-12-17 20:20 UTC, Jacatove requested changes
I think that after clicking on the switch a confirmation message should appear. What do you think about it? @elvinquero

2021-12-18 00:30 UTC, ivanvgh requested changes

2021-12-18 00:34 UTC, ivanvgh requested changes

2021-12-20 14:18 UTC, ivanvgh requested changes

2021-12-20 17:11 UTC, ivanvgh approved these changes

2021-12-20 17:37 UTC, Jacatove approved these changes

2021-12-20 18:01 UTC, merged