PADV-55 - Add Institutions list.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #2
Opened 2021-11-26 12:45 UTC by ivanvgh

### Description:
This PR adds the following:
- store
- feature-based organization
- Institution list

More context in [PADV-50](https://agile-jira.pearson.com/browse/PADV-55).
**Note:** Tests are going to be added in the following PR.

![Screenshot from 2021-11-26 07-45-23](https://user-images.githubusercontent.com/36037715/143583075-cf3762ee-6508-410c-beb1-33534846c32b.png)

2021-11-30 15:35 UTC, elvinquero approved these changes

2021-11-30 16:46 UTC, Jacatove approved these changes
LGTM.
![image](https://user-images.githubusercontent.com/40271196/144089641-d3d49047-c2de-43ad-a49c-608ca134c717.png)

2021-11-30 23:07 UTC, Squirrel18 requested changes

2021-12-01 01:51 UTC, Squirrel18 requested changes

2021-12-01 02:05 UTC, Squirrel18 approved these changes

2021-12-01 02:06 UTC, merged