PADV-34 - export enrollments as CSV
Pearson-Advance/frontend-app-pearson-admin-portal pull request #30
Opened 2022-02-11 22:55 UTC by ivanvgh

### Description:
This PR adds the enrollments export as CSV feature.

Note. The Export as CSV button will be disabled anytime the filters are changed and not applied.

### Demo:

1. Export button enabled 
![Screenshot from 2022-02-11 10-22-09](https://user-images.githubusercontent.com/36037715/153681449-70c0b308-f967-492d-b19a-bc81b847aa35.png)

2. Export button disabled
![Screenshot from 2022-02-11 17-54-16](https://user-images.githubusercontent.com/36037715/153681602-e5d96253-00c2-465f-82a0-e751f9024137.png)

3. Export completed
![Screenshot from 2022-02-11 17-55-15](https://user-images.githubusercontent.com/36037715/153681699-9512f8f5-be9a-48e2-a2fb-ef17d96681f5.png)

2022-02-12 00:44 UTC, Jacatove requested changes
Two comments.
1. After playing around with the changes, I think that other alternative could be to filter dynamically, so if the user changes the filters, then the data is immediately filtered.

2. I didn't catch it during the last review. There are some warnings, Could you please fix these proptypes within this PR?. They are suppose to be strings.
https://github.com/Pearson-Advance/frontend-app-pearson-admin-portal/blob/05c9d15c36e08c894b3c5c013b8e01f4a6a114fa/src/features/enrollments/components/Filters/index.jsx#L135-L136

2022-02-14 13:37 UTC, Jacatove requested changes

2022-02-14 13:48 UTC, anfbermudezme approved these changes

2022-02-14 13:49 UTC, Jacatove approved these changes

2022-02-14 13:51 UTC, merged