PADV-98 - feat: Add sorting feature to Enrollments tab.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #31
Opened 2022-02-16 18:17 UTC by Jacatove

## Description:
This PR adds the sorting and pagination capabilities to the table in the `Enrollments Tab`. The table sorts by:

- institution
- master_course_name
- ccx_coach_email
- learner_email

## Changes:
### Sorting:
![image](https://user-images.githubusercontent.com/40271196/154335371-9ef08018-fdf0-460f-b98f-4f4aab07464c.png)

### Pagination:
![image](https://user-images.githubusercontent.com/40271196/154335498-367b2a53-2326-4974-aa82-59dadaffda05.png)

### Notes for filters and pagination:

- If user clicks on `Clean filters` and a column header has been clicked (ascending/descending), then the result table keeps the sorting criteria with no filters.
- If user clicked on `Apply filter`,and then clicks on a column header, then the result is both filtered with the same criteria as before and sorted according to the sorting option (ascending/descending).
- Pagination keeps both filtering and sorting criteria.

2022-02-17 01:31 UTC, ivanvgh requested changes
I guess you are missing the tests suit as well.

2022-02-17 18:33 UTC, anfbermudezme approved these changes

2022-02-17 20:02 UTC, ivanvgh requested changes

2022-02-17 20:52 UTC, ivanvgh requested changes

2022-02-18 14:45 UTC, ivanvgh approved these changes

2022-02-18 15:27 UTC, merged