PADV-82 - Add CCX level report in data report tab
Pearson-Advance/frontend-app-pearson-admin-portal pull request #32
Opened 2022-02-18 03:54 UTC by ivanvgh

### Description:
This PR adds the data report tab, specifically the CCX level license usage report(Detailed license usage report).

Filtering capability:
- institution
- master course
### Demo:
![Screenshot from 2022-02-18 16-39-20](https://user-images.githubusercontent.com/36037715/154764867-e309112d-0bc9-4c4c-8329-b87523cac387.png)

**Note.** The tests suit will be added in a separate PR because this is big enough.

2022-02-18 18:22 UTC, anfbermudezme approved these changes

2022-02-18 18:36 UTC, Jacatove requested changes
Works as expected, but I am not quite sure about the components distribution. Could you please move both navigation pagination and master course filter to the left.

2022-02-19 00:21 UTC, Jacatove requested changes

2022-02-21 15:09 UTC, Jacatove approved these changes

2022-02-21 16:28 UTC, merged