PADV-102 - add enable, disable and delete approach for enrollments table.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #35
Opened 2022-02-25 15:05 UTC by anfbermudezme

This PR Follow the actions:

Delete - if the enrollment is 'pending'.
Disable - if the enrollment is 'active'
Enable - if the enrollment is 'inactive'

![image](https://user-images.githubusercontent.com/30726391/155738317-ba57088b-8b9d-4f68-a96d-edec7f6d24e9.png)

2022-02-25 16:32 UTC, Jacatove requested changes

2022-02-25 21:02 UTC, ivanvgh requested changes

2022-03-02 13:46 UTC, Jacatove requested changes
I think you are missing some suggestions you already addressed. Could you please review if you pushed all your chnages. @anfbermudezme

2022-03-02 13:59 UTC, Jacatove requested changes

2022-03-03 13:57 UTC, Jacatove requested changes

2022-03-03 17:31 UTC, Jacatove approved these changes

2022-03-03 18:38 UTC, merged