PADV-146 - Filter courses which can not be added for dropdown.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #52
Opened 2022-09-09 01:29 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-146

## Description

This PR extends the license form component to send the necessary parameters to the request of eligible courses and obtain the available courses to add to a license.

Now, when an institution is selected in the form, a request is send to the eligible courses endpoint with the id of the institution as a parameter, instead if a license is being edited, the request will be send with the id of the license as a parameter.

## Testing

- Clone this repository on the devstack src folder.
- Install NPM dependencies: ´npm install´.
- Run the MFE dev server: ´npm start´.
- Go into your devstack and run the lms: ´make.dev.up.lms´.
- Go to the MFE dashboard at http://localhost:8090.

Be sure to checkout to the branch 'vue/PADV-146' on the plugin course_operations https://github.com/Pearson-Advance/course_operations/tree/vue/PADV-146

#### Expected Behavior

- When adding a license: when the institution is selected it should show all the courses that are not associated to the institution.
- When editing a license: all courses already in the license should be shown as well as those not associated to the institution of that license.

### Screenshots

![Screenshot from 2022-10-11 17-40-15](https://user-images.githubusercontent.com/62396424/195211650-eb72b28e-804b-4504-a84e-3b03efd73725.png)
![Screenshot from 2022-10-11 17-40-23](https://user-images.githubusercontent.com/62396424/195211661-61205bf7-7b56-4df8-8edf-935e9fd3cd6e.png)
![Screenshot from 2022-10-11 17-40-40](https://user-images.githubusercontent.com/62396424/195211670-a36d8f9c-d929-4bd7-9ffd-2cd46b90e63f.png)
![Screenshot from 2022-10-11 17-40-47](https://user-images.githubusercontent.com/62396424/195211673-5f74e339-fcff-4e7f-b715-c3c7aa67b8a7.png)
![Screenshot from 2022-10-11 17-39-47](https://user-images.githubusercontent.com/62396424/195211621-a14cfa39-0886-4e40-b438-64259630a40e.png)

## Reviewers

- [ ] @Squirrel18 
- [x] @anfbermudezme 
- [x] @Jacatove 
- [ ] @kuipumu

2022-09-09 02:16 UTC, anfbermudezme requested changes

2022-09-26 19:55 UTC, anfbermudezme approved these changes
LGTM.

2022-09-27 13:57 UTC, Jacatove requested changes
Once you get to the Licenses Tab, the Eligible Course API is called and there is no need to do it. Could you please delete this line? https://github.com/Pearson-Advance/frontend-app-pearson-admin-portal/blob/4a3a7584c9aec98c0e62f9a02d28a6e5b1b205c4/src/features/licenses/components/LicensesPage/index.jsx#L38


Once you click on the Add License button, the Eligible Courses is called again without any purpose. Could you please remove this behavior?. With the parameters support the API should be called only after selecting the Institution while creating or when editing a license.

2022-09-28 04:15 UTC, Jacatove requested changes

2022-09-29 01:25 UTC, Jacatove approved these changes

2022-09-30 20:23 UTC, kuipumu approved these changes

2022-10-11 21:25 UTC, Squirrel18 requested changes

2022-10-12 02:37 UTC, Squirrel18 approved these changes

2022-10-12 15:58 UTC, merged