PADV-33: Add institution admin list.
Pearson-Advance/frontend-app-pearson-admin-portal pull request #8
Opened 2021-12-10 15:10 UTC by elvinquero

This PR adds an institution admin list.

The tests will be added in a following PR.

Reference: [PADV-33](https://agile-jira.pearson.com/browse/PADV-33)

Images:
![admins2](https://user-images.githubusercontent.com/401198/145627096-6d0d0779-0c00-4a3f-818e-19997b98244e.png)

2021-12-10 16:50 UTC, ivanvgh requested changes

2021-12-10 20:30 UTC, ivanvgh requested changes

2021-12-13 18:42 UTC, ivanvgh requested changes

2021-12-13 19:05 UTC, Jacatove requested changes
I was creating institution administrators and found out a possible and remote bug.
Creating institutions administrators with certain emails will raise an error. I guess this is due to the fact that the coach username is based on the email. 
name.lastname@email.com
name.lastname@email2.com
namelastname@email3.com

Do not know if we should be worried, but it is important to be aware of it. 
@elvinquero

2021-12-13 22:47 UTC, ivanvgh requested changes

2021-12-14 13:09 UTC, ivanvgh approved these changes

2021-12-14 13:52 UTC, Jacatove approved these changes

2021-12-14 14:38 UTC, merged